server:
  port: 8000  #定义单点登录的端口
  servlet:    context-path: /   #该配置可以删除,默认配置就是 /
spring:
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/     # /默认代表根目录 src/main/webapp
      suffix: .jsp 
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root  
  application:   #定义服务名称,如果多个相同服务，那么名称必须相同
    name: provider-user
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8000                #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
  
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.user.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml

  
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

  
  